export const SITE_CONFIG = {
  name: 'Watermark AI Remover',
  shortName: 'WatermarkAI',
  description: 'Free AI Watermark & Object Remover. Remove watermarks, logos, timestamps, text, and unwanted objects from images and videos with pixel-exact AI inpainting.',
  url: (typeof import.meta !== 'undefined' && import.meta.env?.VITE_SITE_URL) || 'https://watermarksairemover.com',
  ogImage: '/og-image.png',
  links: {
    twitter: 'https://twitter.com/WatermarksAIRemover',
    github: 'https://github.com/cleanmark-ai'
  },
  supportEmail: 'support@watermarksairemover.com',
  author: 'Watermark AI Media Labs',
  keywords: [
    'watermark remover',
    'ai watermark remover',
    'watermark image remover',
    'remove watermark from image',
    'remove watermark from photo',
    'remove watermark from picture',
    'photo watermark remover',
    'picture watermark remover',
    'image watermark remover',
    'free watermark remover',
    'watermark remover free',
    'watermark remover online',
    'free watermark remover online',
    'ai watermark remover online',
    'remove watermark online free',
    'erase watermark from photo',
    'erase watermark from image',
    'watermark eraser',
    'watermark eraser online',
    'watermark cleaner',
    'watermark deleter',
    'remove logo from image',
    'remove text from image',
    'remove text from photo',
    'remove stamp from photo',
    'date stamp remover',
    'transparent watermark remover',
    'remove watermark without blur',
    'remove watermark without losing quality',
    'clean watermark ai',
    'best watermark remover',
    'best ai watermark remover',
    'video watermark remover',
    'remove watermark from video online',
    'tiktok watermark remover',
    'shutterstock watermark remover',
    'get rid of watermark',
    'ai inpainting watermark remover',
    'batch watermark remover',
    'remove copyright watermark from image',
    'online watermark remover hd',
    'magic watermark remover',
    'unwatermark image ai',
    'photo stamp remover online',
    'free ai photo watermark cleaner'
  ],
  limits: {
    maxImageSizeMB: 25,
    maxImageDimension: 5000,
    maxVideoSizeMB: 100,
    supportedImageFormats: ['PNG', 'JPEG', 'JPG', 'WebP'],
    supportedVideoFormats: ['MP4', 'MOV', 'WebM']
  }
};
